[package]
name = "santorini-ai"
version = "0.1.0"
authors = ["Joshua Brot <jbrot@umich.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.0"
tui = "0.13"
termion = "1.5"
